### PR TITLE
Implements ability to specify a color for getGlyphImage.

### PR DESCRIPTION
**Pull request by dom96**

### CODE REVIEW

**Comment by treeform** [comment]
So I am not a huge fan of setting the color on the generate glyph image. Rastarazing is very slow you would not want to do it for each color, instead you would want to tint it during drawing, for speed.

(Yes if you never change text color, tinting is faster, but its not very flexible)

You would do that either just multiplying by the color in a shader:
```glsl
fragColor = texture(rgbaTex, uv).rgba * color;
```

or using some thing like https://wiki.libsdl.org/SDL_SetTextureColorMod in SDL.
```nim
        discard glyphEntry.texture.setTextureColorMod(255, 0, 0)
        sdl2.copy(render, glyphEntry.texture, nil, addr destRect)
```
image

or even flippys `image.blitWithMask`

I am also not a huge fan of setting line height to glyph height. Yes you can forget to set line height and text will come out all funny. But I need to be able to support setting line height to less then glyph height.

image

Maybe if its set to 0 or -1 or some thing then use glyph height. But here I still don't feel its good. Its just too surprising ... you set line height to 0 and you get 0. Its what it is.

**Comment by treeform** [comment]
See: https://github.com/treeform/typography/blob/master/tests/sdlexample.nim

**Comment by dom96** [comment]
Ahh, thanks for the code samples regarding colour. I'll try to switch to that and see how performance compares. For now I'll just use my fork.

> Its just too surprising ... you set line height to 0 and you get 0. Its what it is.

Fair enough, but then how do I get the height of my text? That's all I want.

**Comment by treeform** [comment]
> how do I get the height of my text?

Just call `textBounds` on either a string or a layout (other wise it would create another layout) it will give you width and height.

https://github.com/treeform/typography/blob/73fe3c85e836ead39429d23e68259c62c8d31405/src/typography/layout.nim#L310

But you need to set lineHeight first. I would just set that to the fontSize + some spacing when you set that?  

Do you mean how do I get default lineHeight that font creator intended of font based on the fontSize?
I don't know right now, i'll research the topic.

**Comment by treeform** [comment]
Does not like like SVG fonts support getting intended line height: https://www.w3.org/TR/SVG11/fonts.html

It looks like TTF do through the hhea.lineGap .

It looks by default browser set line-height at *1.2 of font size: https://developer.mozilla.org/en-US/docs/Web/CSS/line-height

I am not sure how to handle this `normal` line height maybe another boolean is needed to set if normal or not normal ... I don't like it.

**Comment by treeform** [comment]
I added a concept of a `normalLineHeight` so when lineHeight == normalLineHeight it defaults to lineHeight = floor(font.size * 1.2)

I think this is will be enough.

https://github.com/treeform/typography/commit/3e829f9d096aa7b34d4761f8cd480ff0ce465087

**Comment by dom96** [comment]
I want precisely the maximum `glyphSize.y`, the code I'm using here gives precisely what I want. 

Indeed, even browsers have this limitation where they will not allow you to measure the actual real height of a line of text, don't repeat their mistakes :)

`font.size * 1.2` does not seem like what I want, it seems like an approximation. If I draw a line of text, call `textBounds` on its layout and draw a box for those textBounds then the edges of that box should be precisely around my text. To help visualise this, here is the output of my [font_render example](https://github.com/dom96/gamelight/blob/master/examples/font_render.nim):

Screen Shot 2020-01-13 at 21 05 19

That's what I believe `textBounds` should return.

**Comment by treeform** [comment]
Sorry that Image still does not make it clear what you want. Do you want some thing like minimum ink binding rectangle? Here are 3 examples:

image

This is what I give you (or more like you set these things for display)
image

Maybe you just want the just `accent` height?
image
from https://developer.apple.com/library/archive/documentation/TextFonts/Conceptual/CocoaTextArchitecture/FontHandling/FontHandling.html

**Comment by treeform** [comment]
I expose some of these values:

```nim
  Font* = ref object
    ## Main font object contains font information and Glyphs
    filename*: string
    name*: string
    bboxMin*: Vec2
    bboxMax*: Vec2
    advance*: float
    ascent*: float
    descent*: float
    xHeight*: float
    capHeight*: float
    unitsPerEm*: float
```
its in "units" scale you will have to convert with this:
```nim
    fontHeight = font.ascent - font.descent
    scale = font.size / fontHeight
```

**Comment by dom96** [comment]
Thanks for the thorough answers @treeform. It does appear that I simply want the font size, I didn't think about the case with `...` which would be mis-rendered with my current calculations. I'll get back to this once I finish the rest of the game and continue to use this fork for now.

**Comment by dom96** [comment]
@treeform  In the end I was able to use the `ascent` to get what I need. So layout and colours all work for me. The only problem remaining that I noticed is that `!` (exclamation marks) are not rendered, have you seen something like this happen?

Anyway, closing this.

**Pull request closed without merging**
